'use client';

import React, { useState, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { 
  Send, 
  Plus, 
  Loader2, 
  BookOpen, 
  ShieldAlert,
  ArrowRight,
  SlidersHorizontal,
  Paperclip,
  Mic,
  ArrowDown,
  FileText,
  Cpu,
  CornerDownLeft,
  ChevronDown
} from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { useChat } from '@/context/ChatContext';
import { apiService } from '@/services/api';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  message: string;
  created_at: string;
}

function ChatConsoleInner() {
  const { user, profile, loading: authLoading } = useAuth();
  const { chats, loadChatHistory } = useChat();
  const router = useRouter();
  const searchParams = useSearchParams();
  
  // URL parameter chat id
  const chatIdParam = searchParams.get('id');

  const [activeChatId, setActiveChatId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputMessage, setInputMessage] = useState('');
  const [streamingMessage, setStreamingMessage] = useState('');
  const [loadingMessages, setLoadingMessages] = useState(false);
  const [isStreaming, setIsStreaming] = useState(false);
  const [errorBanner, setErrorBanner] = useState('');

  // RAG references for the current query
  const [citations, setCitations] = useState<any[]>([]);
  const [tokenMetrics, setTokenMetrics] = useState<{
    prompt_tokens: number;
    completion_tokens: number;
    model: string;
  } | null>(null);

  // Tab active state for each message
  const [messageTabs, setMessageTabs] = useState<Record<string, 'answer' | 'citations' | 'steps'>>({});

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const chatContainerRef = useRef<HTMLDivElement>(null);
  const [showScrollBottom, setShowScrollBottom] = useState(false);

  // Auto-scroll to bottom of chat
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  // Monitor scroll height to show/hide the scroll-down action button
  const handleScroll = () => {
    if (!chatContainerRef.current) return;
    const { scrollTop, scrollHeight, clientHeight } = chatContainerRef.current;
    const isNearBottom = scrollHeight - scrollTop - clientHeight < 150;
    setShowScrollBottom(!isNearBottom && scrollHeight > clientHeight);
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, streamingMessage]);

  const loadMessages = async (id: string) => {
    try {
      setLoadingMessages(true);
      setErrorBanner('');
      const data = await apiService.getChatMessages(id);
      setMessages(data);
      
      // Clean citations and token metrics when switching rooms
      setCitations([]);
      setTokenMetrics(null);
    } catch (err) {
      console.error('Failed to fetch messages:', err);
      setErrorBanner('Failed to load messages.');
    } finally {
      setLoadingMessages(false);
    }
  };

  // Synchronize with Auth status and URL search queries
  useEffect(() => {
    if (!authLoading && !user) {
      router.push('/login');
    }
  }, [user, authLoading, router]);

  useEffect(() => {
    if (chatIdParam) {
      setActiveChatId(chatIdParam);
      loadMessages(chatIdParam);
    } else {
      // Clear active conversations if no id parameter
      setActiveChatId(null);
      setMessages([]);
      setCitations([]);
      setTokenMetrics(null);
    }
  }, [chatIdParam]);

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputMessage.trim() || isStreaming) return;

    const messageText = inputMessage.trim();
    setInputMessage('');
    setErrorBanner('');
    setIsStreaming(true);
    setStreamingMessage('');

    // Pre-insert user message locally into UI state
    const tempUserMsg: Message = {
      id: Math.random().toString(),
      role: 'user',
      message: messageText,
      created_at: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, tempUserMsg]);

    // Stream chat orchestrator
    await apiService.streamChat(messageText, activeChatId, {
      onInit: (initData) => {
        // If a new chat session was generated by backend, push ID to browser query
        if (!activeChatId) {
          setActiveChatId(initData.chat_id);
          router.replace(`/chat?id=${initData.chat_id}`);
        }
        setCitations(initData.citations);
      },
      onChunk: (chunkText) => {
        setStreamingMessage((prev) => prev + chunkText);
      },
      onMetadata: (metadata) => {
        setTokenMetrics(metadata);
      },
      onError: (err) => {
        setErrorBanner(err);
        setIsStreaming(false);
      },
      onDone: () => {
        setIsStreaming(false);
        if (activeChatId) {
          loadMessages(activeChatId);
        } else if (chatIdParam) {
          loadMessages(chatIdParam);
        }
        setStreamingMessage('');
        loadChatHistory();
      },
    });
  };

  const handleTabChange = (messageId: string, tab: 'answer' | 'citations' | 'steps') => {
    setMessageTabs((prev) => ({
      ...prev,
      [messageId]: tab,
    }));
  };

  if (authLoading) {
    return (
      <div className="min-h-screen bg-[#1e1e1f] flex items-center justify-center text-zinc-500">
        <Loader2 className="w-8 h-8 animate-spin text-amber-500" />
      </div>
    );
  }

  // Sample static steps for the RAG pipeline reasoning
  const getPipelineSteps = (tokens: any) => [
    { name: '1. Semantic Query Extraction', desc: 'Gemini parsed context embeddings mapping tat-psychology vectors.' },
    { name: '2. Vector Store Retrieve', desc: 'Pinecone returned top 3 matches with >85% cosine similarity.' },
    { name: '3. OLQ Criteria Injection', desc: 'Context formatted with active Officer Like Qualities (OLQ) rules.' },
    { name: '4. Gemini Synthesis', desc: tokens ? `Prompt token cost ${tokens.prompt_tokens}, reply cost ${tokens.completion_tokens} using ${tokens.model}.` : 'Synthesizing response utilizing LLM context parameters.' }
  ];

  return (
    <div className="flex flex-col h-full bg-[#1e1e1f] text-zinc-100 relative">
      
      {/* Error banner */}
      {errorBanner && (
        <div className="px-6 py-2.5 bg-rose-500/10 border-b border-rose-500/20 text-rose-400 text-xs font-semibold flex items-center gap-2 flex-shrink-0">
          <ShieldAlert className="w-4 h-4 flex-shrink-0" />
          <span>{errorBanner}</span>
        </div>
      )}

      {/* Message logs area */}
      <div 
        ref={chatContainerRef}
        onScroll={handleScroll}
        className="flex-1 overflow-y-auto px-4 md:px-6 py-6 space-y-6 scrollbar"
      >
        {loadingMessages ? (
          <div className="flex flex-col items-center justify-center py-20 text-zinc-500 gap-2">
            <Loader2 className="w-6 h-6 animate-spin text-amber-500" />
            <span className="text-xs">Loading conversational history...</span>
          </div>
        ) : messages.length === 0 && !streamingMessage ? (
          <div className="max-w-2xl mx-auto py-16 text-center flex flex-col items-center gap-5">
            <div className="w-14 h-14 rounded-2xl bg-amber-500/5 border border-amber-500/10 flex items-center justify-center text-amber-500 mb-2">
              <BookOpen className="w-7 h-7" />
            </div>
            <div>
              <h3 className="font-extrabold text-xl text-white">Ask your SSB AI Mentor</h3>
              <p className="text-xs text-zinc-400 leading-relaxed max-w-md mx-auto mt-1">
                You can ask questions regarding psychological testing (TAT/WAT/SRT), Interview guidelines, GTO obstacles, and general criteria of the 15 Officer Like Qualities (OLQ).
              </p>
            </div>
            
            <div className="grid sm:grid-cols-2 gap-3 mt-4 w-full">
              {[
                "What are the 15 Officer Like Qualities (OLQs)?",
                "How should I tackle a Situation Reaction Test (SRT)?",
                "What questions are asked in the Personal Interview?",
                "Explain GTO Command Task procedures."
              ].map((prompt, idx) => (
                <button
                  key={idx}
                  onClick={() => setInputMessage(prompt)}
                  className="p-3 text-left rounded-xl border border-zinc-900 bg-[#131313]/60 hover:bg-[#131313] text-xs text-zinc-400 hover:text-zinc-200 transition-all font-semibold leading-normal"
                >
                  {prompt}
                </button>
              ))}
            </div>
          </div>
        ) : (
          <div className="space-y-6 max-w-4xl mx-auto">
            {messages.map((msg, index) => {
              const isLastMessage = index === messages.length - 1;
              const isUser = msg.role === 'user';
              const activeTab = messageTabs[msg.id] || 'answer';

              if (isUser) {
                return (
                  <div key={msg.id} className="flex flex-col items-end">
                    <span className="text-[9px] text-zinc-500 font-bold mb-1 uppercase tracking-wider">
                      Candidate
                    </span>
                    <div className="p-3.5 px-4 rounded-2xl max-w-[85%] text-xs md:text-sm leading-relaxed bg-[#282828] border border-zinc-800 text-zinc-100 rounded-tr-none shadow-sm font-medium">
                      {msg.message}
                    </div>
                  </div>
                );
              }

              // Assistant message card with tab layout
              const hasCitations = isLastMessage && citations.length > 0;
              
              return (
                <div key={msg.id} className="flex flex-col items-start w-full">
                  <span className="text-[9px] text-zinc-500 font-bold mb-1 uppercase tracking-wider">
                    SSB AI Coach
                  </span>
                  
                  <div className="w-full max-w-[90%] md:max-w-[85%] bg-[#131313] border border-zinc-900 rounded-2xl rounded-tl-none overflow-hidden shadow-md">
                    {/* Message Tabs Header */}
                    <div className="flex border-b border-zinc-900 bg-[#0f0f0f] px-3">
                      <button
                        onClick={() => handleTabChange(msg.id, 'answer')}
                        className={`py-2.5 px-4 text-xs font-bold transition-all flex items-center gap-1.5 border-b-2 -mb-[1px] ${
                          activeTab === 'answer'
                            ? 'border-amber-500 text-amber-500'
                            : 'border-transparent text-zinc-400 hover:text-zinc-300'
                        }`}
                      >
                        Answer
                      </button>
                      <button
                        onClick={() => handleTabChange(msg.id, 'citations')}
                        className={`py-2.5 px-4 text-xs font-bold transition-all flex items-center gap-1.5 border-b-2 -mb-[1px] ${
                          activeTab === 'citations'
                            ? 'border-amber-500 text-amber-500'
                            : 'border-transparent text-zinc-400 hover:text-zinc-300'
                        }`}
                      >
                        Related Content
                      </button>
                      <button
                        onClick={() => handleTabChange(msg.id, 'steps')}
                        className={`py-2.5 px-4 text-xs font-bold transition-all flex items-center gap-1.5 border-b-2 -mb-[1px] ${
                          activeTab === 'steps'
                            ? 'border-amber-500 text-amber-500'
                            : 'border-transparent text-zinc-400 hover:text-zinc-300'
                        }`}
                      >
                        Steps
                      </button>
                    </div>

                    {/* Message Tabs Body */}
                    <div className="p-4 md:p-5 text-xs md:text-sm leading-relaxed text-zinc-200">
                      
                      {/* TAB 1: Answer */}
                      {activeTab === 'answer' && (
                        <div className="whitespace-pre-wrap font-medium text-zinc-300">
                          {msg.message}
                        </div>
                      )}

                      {/* TAB 2: Related Content (Citations) */}
                      {activeTab === 'citations' && (
                        <div className="space-y-3.5">
                          {hasCitations ? (
                            <div className="grid gap-2.5">
                              <span className="block text-[10px] text-zinc-500 uppercase font-bold tracking-wider">Matched RAG Citations</span>
                              {citations.map((cite, idx) => (
                                <div key={idx} className="p-3 rounded-xl border border-zinc-900 bg-[#181818]/60 space-y-1 hover:border-zinc-800 transition-colors">
                                  <div className="flex items-center justify-between">
                                    <span className="inline-flex items-center px-1.5 py-0.5 rounded bg-amber-500/10 border border-amber-500/20 text-amber-500 text-[9px] font-bold">
                                      Ref [{idx + 1}]
                                    </span>
                                    <span className="text-[9px] text-zinc-500">Page {cite.page || 1}</span>
                                  </div>
                                  <h4 className="font-bold text-xs text-zinc-200 mt-1">
                                    {cite.title || 'Referenced Documentation'}
                                  </h4>
                                  <div className="text-[10px] text-zinc-500 truncate">
                                    Category: <span className="text-zinc-400 font-semibold">{cite.source?.split('/')?.[0] || 'Ingested Files'}</span>
                                  </div>
                                </div>
                              ))}
                            </div>
                          ) : (
                            <div className="text-center py-6 text-zinc-500 text-xs">
                              {isLastMessage ? 'No vector documents retrieved for this prompt.' : 'Citations archived for this conversation.'}
                            </div>
                          )}
                        </div>
                      )}

                      {/* TAB 3: Steps */}
                      {activeTab === 'steps' && (
                        <div className="space-y-3">
                          <span className="block text-[10px] text-zinc-500 uppercase font-bold tracking-wider mb-1">Reasoning Pipeline</span>
                          <div className="space-y-2 border-l border-zinc-800 ml-1.5 pl-3.5">
                            {getPipelineSteps(isLastMessage ? tokenMetrics : null).map((step, idx) => (
                              <div key={idx} className="relative">
                                {/* Bullet indicator */}
                                <div className="absolute -left-[20px] top-1.5 w-2 h-2 rounded-full bg-amber-500/60 border border-[#131313]" />
                                <span className="font-bold text-zinc-200 text-xs block">{step.name}</span>
                                <span className="text-[10px] text-zinc-500 block mt-0.5 leading-normal">{step.desc}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                    </div>
                  </div>
                </div>
              );
            })}

            {/* Streaming Message (typing...) */}
            {streamingMessage && (
              <div className="flex flex-col items-start w-full">
                <span className="text-[9px] text-zinc-500 font-bold mb-1 uppercase tracking-wider">
                  SSB AI Coach (typing...)
                </span>
                <div className="w-full max-w-[90%] md:max-w-[85%] bg-[#131313] border border-zinc-900 rounded-2xl rounded-tl-none overflow-hidden shadow-md">
                  <div className="flex border-b border-zinc-900 bg-[#0f0f0f] px-3">
                    <button className="py-2.5 px-4 text-xs font-bold border-b-2 border-amber-500 text-amber-500">
                      Answer
                    </button>
                  </div>
                  <div className="p-4 md:p-5 text-xs md:text-sm leading-relaxed text-zinc-300 whitespace-pre-wrap font-medium">
                    {streamingMessage}
                    <span className="inline-block w-1.5 h-3 bg-amber-500 ml-1 animate-pulse" />
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Floating Scroll to Bottom Action Button */}
      {showScrollBottom && (
        <button
          onClick={scrollToBottom}
          className="fixed bottom-28 right-8 z-30 w-9 h-9 rounded-full bg-amber-500/10 hover:bg-amber-500/20 border border-amber-500/20 text-amber-500 flex items-center justify-center transition-all shadow-md backdrop-blur-sm hover:scale-105 cursor-pointer"
          title="Scroll down"
        >
          <ArrowDown className="w-4 h-4" />
        </button>
      )}

      {/* Bottom Floating Chat Input Area */}
      <div className="p-4 border-t border-zinc-900/60 bg-[#1e1e1f] flex-shrink-0">
        <form onSubmit={handleSendMessage} className="max-w-4xl mx-auto">
          <div className="bg-[#131313] border border-zinc-900 rounded-2xl shadow-lg p-2.5 flex flex-col focus-within:border-amber-500/30 transition-colors">
            
            {/* Input field */}
            <input
              type="text"
              value={inputMessage}
              onChange={(e) => setInputMessage(e.target.value)}
              disabled={isStreaming}
              placeholder={isStreaming ? "Awaiting assistant response..." : "Ask anything..."}
              className="px-3 py-2 bg-transparent text-zinc-100 text-sm focus:outline-none disabled:text-zinc-600 placeholder-zinc-600"
            />
            
            {/* Tools footer bar inside container */}
            <div className="flex items-center justify-between pt-2 px-1 border-t border-zinc-900/60 mt-1 select-none">
              
              {/* Left utility icons */}
              <div className="flex items-center gap-1">
                <button 
                  type="button"
                  title="Prompt Settings"
                  className="p-1.5 text-zinc-600 hover:text-zinc-300 rounded-lg hover:bg-zinc-800/40 transition-colors"
                >
                  <SlidersHorizontal className="w-3.5 h-3.5" />
                </button>
                <button 
                  type="button"
                  title="Attach Documents"
                  className="p-1.5 text-zinc-600 hover:text-zinc-300 rounded-lg hover:bg-zinc-800/40 transition-colors"
                >
                  <Paperclip className="w-3.5 h-3.5" />
                </button>
                <button 
                  type="button"
                  title="Voice Input"
                  className="p-1.5 text-zinc-600 hover:text-zinc-300 rounded-lg hover:bg-zinc-800/40 transition-colors"
                >
                  <Mic className="w-3.5 h-3.5" />
                </button>
              </div>

              {/* Right Send icon */}
              <button
                type="submit"
                disabled={isStreaming || !inputMessage.trim()}
                className="w-8 h-8 rounded-full bg-[#f0a924] hover:bg-[#e09b1f] disabled:bg-zinc-800 disabled:text-zinc-600 text-black flex items-center justify-center transition-all hover:scale-105"
              >
                {isStreaming ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Send className="w-3.5 h-3.5 stroke-[2.5]" />
                )}
              </button>

            </div>
          </div>
        </form>
      </div>

    </div>
  );
}

export default function ChatConsole() {
  return (
    <React.Suspense fallback={
      <div className="min-h-screen bg-[#1e1e1f] flex items-center justify-center text-zinc-500">
        <Loader2 className="w-8 h-8 animate-spin text-amber-500" />
      </div>
    }>
      <ChatConsoleInner />
    </React.Suspense>
  );
}

